# Generated by Django 4.2.9 on 2024-05-03 19:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=300, verbose_name='Username')),
                ('super_access', models.BooleanField(default=False, verbose_name='Суперадмин')),
                ('admin_access', models.BooleanField(default=False, verbose_name='Админ')),
                ('author_access', models.BooleanField(default=False, verbose_name='Автор')),
                ('surname', models.CharField(blank=True, max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=50, verbose_name='Отчества')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('birthplace', models.CharField(blank=True, max_length=200, verbose_name='Место рождения')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описаниеs')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=profiles.models.make_upload_path, verbose_name='Аватарка')),
                ('registration_date', models.DateField(default=datetime.date.today, verbose_name='Registration date')),
                ('user', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['surname', 'name', 'middlename'],
            },
        ),
    ]
