# Generated by Django 4.2.9 on 2024-05-13 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_remove_profile_birthday'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='birthplace',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
    ]
