# Generated by Django 4.2.9 on 2024-05-26 11:15

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Ответ')),
                ('text', models.TextField(max_length=400, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CommentUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(null=True, verbose_name='Описание комментария')),
                ('User', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Комментарий пользователя',
                'verbose_name_plural': 'Комментарии пользователя',
                'ordering': ['text'],
            },
        ),
        migrations.CreateModel(
            name='RatingComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_digit', models.IntegerField()),
                ('comment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.commentuser', verbose_name='Комментарий')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Вопрос пользователя')),
            ],
            options={
                'verbose_name': 'Рейтинг комментария',
                'verbose_name_plural': 'Рейтинги комментариев',
                'ordering': ['comment'],
            },
        ),
        migrations.CreateModel(
            name='RatingAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating_digit', models.IntegerField()),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.answers', verbose_name='Комментарий')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Вопрос пользователя')),
            ],
            options={
                'verbose_name': 'Рейтинг ответа',
                'verbose_name_plural': 'Рейтинги ответов',
                'ordering': ['answer'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(default=datetime.datetime(2024, 5, 26, 14, 15, 9, 704512), verbose_name='Дата создание вопроса')),
                ('user_quest', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Вопрос пользователя')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='answers',
            name='comment',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='questions.commentuser', verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.questions', verbose_name='Вопрос'),
        ),
        migrations.AddField(
            model_name='answers',
            name='rating',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.PROTECT, to='questions.ratinganswer', verbose_name='Рейтинг'),
        ),
        migrations.AddField(
            model_name='answers',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Вопрос пользователя'),
        ),
    ]
