# Generated by Django 4.2.9 on 2024-05-26 11:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='comment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.commentuser', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.ratinganswer', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='text',
            field=models.TextField(blank=True, verbose_name='Описание комментария'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 26, 14, 18, 16, 723494), verbose_name='Дата создание вопроса'),
        ),
        migrations.AlterField(
            model_name='ratinganswer',
            name='answer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='questions.answers', verbose_name='Комментарий'),
        ),
    ]
