# Generated by Django 4.2.9 on 2024-06-06 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_answers_user_alter_questions_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 21, 36, 23, 410107), verbose_name='Дата создание вопроса'),
        ),
    ]
