# Generated by Django 4.2.9 on 2024-06-06 18:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_alter_questions_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.commentuser', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='rating',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.ratinganswer', verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 6, 21, 37, 26, 34276), verbose_name='Дата создание вопроса'),
        ),
        migrations.AlterField(
            model_name='ratinganswer',
            name='answer',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='questions.answers', verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='ratingcomment',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.commentuser', verbose_name='Комментарий'),
        ),
    ]
