# Generated by Django 4.2.9 on 2024-06-16 21:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_alter_answers_comment_alter_answers_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 0, 14, 48, 849602), verbose_name='Дата создание вопроса'),
        ),
        migrations.AddField(
            model_name='commentuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 0, 14, 48, 849082), verbose_name='Дата создание вопроса'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 17, 0, 14, 48, 848620), verbose_name='Дата создание вопроса'),
        ),
    ]
