# Generated by Django 4.2.9 on 2024-06-18 18:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_answers_created_at_commentuser_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentuser',
            name='answer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='questions.answers', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answers',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 21, 34, 3, 830091), verbose_name='Дата создание ответа'),
        ),
        migrations.AlterField(
            model_name='commentuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 21, 34, 3, 829526), verbose_name='Дата создание комментария'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 6, 18, 21, 34, 3, 829018), verbose_name='Дата создание вопроса'),
        ),
    ]
