# Generated by Django 4.2.9 on 2024-05-19 12:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=250, verbose_name='')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=50, verbose_name='Отчества')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('birthplace', models.CharField(blank=True, max_length=200, verbose_name='Место рождения')),
                ('deathday', models.DateField(blank=True, verbose_name='Дата смерти')),
                ('deathlace', models.CharField(blank=True, max_length=200, verbose_name='Место смерти')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Аватарка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
            ],
            options={
                'verbose_name': 'Публицист',
                'verbose_name_plural': 'Публицисты',
                'ordering': ['-birthday'],
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=350, verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
