# Generated by Django 4.2.9 on 2024-05-19 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='deathday',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата смерти'),
        ),
        migrations.AlterField(
            model_name='authors',
            name='deathlace',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='Место смерти'),
        ),
    ]
