# Generated by Django 4.2.9 on 2024-05-21 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_post_remove_authors_is_published_answers_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Запись', 'verbose_name_plural': 'Записи'},
        ),
    ]
