# Generated by Django 4.2.9 on 2024-05-07 22:19

import datetime
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='Имя')),
                ('middlename', models.CharField(blank=True, max_length=50, verbose_name='Отчества')),
                ('birthday', models.DateField(default=datetime.date.today, verbose_name='Дата рождения')),
                ('birthplace', models.CharField(blank=True, max_length=200, verbose_name='Место рождения')),
                ('deathday', models.DateField(blank=True, verbose_name='Дата смерти')),
                ('deathlace', models.CharField(blank=True, max_length=200, verbose_name='Место смерти')),
                ('description', models.TextField(blank=True, verbose_name='Краткое описание')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='authors/', verbose_name='Аватарка')),
                ('slug', models.SlugField(null=True)),
            ],
            options={
                'verbose_name': 'Публицист',
                'verbose_name_plural': 'Публицисты',
                'ordering': ['-birthday'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=150)),
                ('content', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='service.questions', verbose_name='Родительская категория')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
    ]
